---
- name: Add ansible user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    groups: sudo
    append: yes
  ignore_unreachable: yes
  register: connectivity
- name: Set ansible user authorized_keys
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ ssh_deploy_key }}"
  when: connectivity.skip_reason is not defined
- name: allow ansible to use sudo with NOPASSWD
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^ansible ALL='
    insertafter: EOF # inserts line at the end of the file
    line: "{{ ansible_sudoers_config }}"
    validate: '/usr/sbin/visudo -cf %s'
  when: connectivity.skip_reason is not defined
- name: disable ssh as root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^\#?PermitRootLogin yes'
    line: 'PermitRootLogin no'
  when: connectivity.skip_reason is not defined
  notify: [ restart ssh server ]
- name: Disable root password
  user:
    name: root
    password: '!'
  when: connectivity.skip_reason is not defined